### ISSUE TITLE
[Example] Login with Devise

### ISSUE THREAD

**Issue by excid3** [excid3/betterminitest.com#1]
Show how to login in a user in your tests.

```ruby
class ActionDispatch::IntegrationTest
  include Devise::Test::IntegrationHelpers
end
```

**Comment by excid3** [comment]
Add example for fixture passwords with Devise

```yaml
default:
  email: user@example.com
  encrypted_password: <%= Devise::Encryptor.digest(User, 'password') %>
```
