### ISSUE TITLE
[Example] Fixtures with Blind Indexes

### ISSUE THREAD

**Issue by tbcooney** [excid3/betterminitest.com#10]
```
one:
  email_ciphertext: <%= User.generate_email_ciphertext("secret@example.com").inspect %>
  email_bidx: <%= User.generate_email_bidx("secret@example.com").inspect %>
  first_name_ciphertext: <%= User.generate_first_name_ciphertext("John").inspect %>
  last_name_ciphertext: <%= User.generate_last_name_ciphertext("Doe").inspect %>
  encrypted_password: <%= Devise::Encryptor.digest(User, 'password') %>
  time_zone: "America/Chicago"
  
  # If using Devise::Confirmable
  confirmed_at: <%= Time.current %>
```
